<?php

global $_MODULE;
$_MODULE = array();

$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Internauten Product AI')] = 'Internauten Product AI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Erzeugt per ChatGPT eine Produktbeschreibung direkt im PrestaShop-Admin.')] = 'Erzeugt per ChatGPT eine Produktbeschreibung direkt im PrestaShop-Admin.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Einstellungen wurden gespeichert.')] = 'Die Einstellungen wurden gespeichert.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI-Einstellungen')] = 'OpenAI-Einstellungen';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI API Key')] = 'OpenAI API Key';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Trage hier deinen OpenAI API Key ein.')] = 'Trage hier deinen OpenAI API Key ein.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Modell')] = 'Modell';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Empfohlen: gpt-4o-mini')] = 'Empfohlen: gpt-4o-mini';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('System-Prompt')] = 'System-Prompt';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Definiert Rolle, Stil und Verhalten des Modells.')] = 'Definiert Rolle, Stil und Verhalten des Modells.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Prompt-Vorlage')] = 'Prompt-Vorlage';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Nutze {{product_name}} als Platzhalter für den Artikelnamen.')] = 'Nutze {{product_name}} als Platzhalter für den Artikelnamen.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Speichern')] = 'Speichern';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Mit ChatGPT generieren')] = 'Mit ChatGPT generieren';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Beschreibung wird erstellt...')] = 'Beschreibung wird erstellt...';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Bitte zuerst einen Artikelnamen eintragen.')] = 'Bitte zuerst einen Artikelnamen eintragen.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Beschreibung konnte nicht generiert werden.')] = 'Die Beschreibung konnte nicht generiert werden.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Fehler bei der Generierung.')] = 'Fehler bei der Generierung.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Der Server hat keine gültige JSON-Antwort geliefert:')] = 'Der Server hat keine gültige JSON-Antwort geliefert:';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('leere Antwort')] = 'leere Antwort';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Es ist kein OpenAI API Key hinterlegt.')] = 'Es ist kein OpenAI API Key hinterlegt.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die PHP-cURL-Erweiterung ist auf dem Server nicht aktiviert.')] = 'Die PHP-cURL-Erweiterung ist auf dem Server nicht aktiviert.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI konnte nicht erreicht werden: ')] = 'OpenAI konnte nicht erreicht werden: ';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Unbekannter API-Fehler.')] = 'Unbekannter API-Fehler.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI hat keine Beschreibung zurückgegeben.')] = 'OpenAI hat keine Beschreibung zurückgegeben.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Du bist ein professioneller E-Commerce-Texter mit sommelier-artigem Stil und Fokus auf hochwertige Spirituosen, insbesondere Whisky. Erstelle elegante, sensorische und glaubwürdige HTML-Produktbeschreibungen für deutschsprachige Onlineshops. Betone bei Whisky – sofern aus dem Produktnamen plausibel ableitbar – Herkunft, Reifung, Duftbild, Geschmacksprofil, Textur und Nachklang. Wenn Details fehlen, bleibe stilvoll und allgemein, ohne Fakten zu erfinden. Die Sprache soll genussorientiert, präzise und hochwertig sein, aber nie übertrieben oder pathetisch. Antworte ausschließlich mit sauberem HTML ohne Markdown-Codeblöcke.')] = 'Du bist ein professioneller E-Commerce-Texter mit sommelier-artigem Stil und Fokus auf hochwertige Spirituosen, insbesondere Whisky. Erstelle elegante, sensorische und glaubwürdige HTML-Produktbeschreibungen für deutschsprachige Onlineshops. Betone bei Whisky – sofern aus dem Produktnamen plausibel ableitbar – Herkunft, Reifung, Duftbild, Geschmacksprofil, Textur und Nachklang. Wenn Details fehlen, bleibe stilvoll und allgemein, ohne Fakten zu erfinden. Die Sprache soll genussorientiert, präzise und hochwertig sein, aber nie übertrieben oder pathetisch. Antworte ausschließlich mit sauberem HTML ohne Markdown-Codeblöcke.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5("Erstelle für das Produkt \"{{product_name}}\" eine sommelier-artige Produktbeschreibung für einen deutschsprachigen Onlineshop mit Fokus auf Whisky und Premium-Spirituosen.\n\nInhalt:\n- beschreibe den Whisky mit einer eleganten, sensorischen und genussorientierten Sprache\n- gehe, wenn aus dem Namen erkennbar, auf Herkunft, Fassreifung, Duft, Geschmack, Mundgefühl und Nachklang ein\n- stelle Charakter und Stil des Produkts hochwertig dar, ohne erfundene Fakten zu ergänzen\n- vermittle, zu welchem Genussmoment oder Anlass der Whisky besonders gut passt\n\nFormat:\n- gib ausschließlich sauberes HTML für die PrestaShop-Produktbeschreibung zurück\n- beginne mit einem atmosphärischen Absatz in <p>\n- ergänze eine Zwischenüberschrift in <h3> wie Verkostungsnotizen oder Charakter\n- füge 4 bis 6 prägnante Stichpunkte in einer <ul> mit <li>-Elementen ein\n- schließe mit einem kurzen, stilvollen Absatz zum Finish oder Genussmoment ab\n\nStil:\n- sommelier-artig, präzise, hochwertig und vertrauenswürdig\n- bildhaft und genussvoll, aber nicht kitschig oder übertrieben\n- keine Fantasieangaben, keine Hinweise auf KI, keine Emojis, keine Markdown-Codeblöcke")] = "Erstelle für das Produkt \"{{product_name}}\" eine sommelier-artige Produktbeschreibung für einen deutschsprachigen Onlineshop mit Fokus auf Whisky und Premium-Spirituosen.\n\nInhalt:\n- beschreibe den Whisky mit einer eleganten, sensorischen und genussorientierten Sprache\n- gehe, wenn aus dem Namen erkennbar, auf Herkunft, Fassreifung, Duft, Geschmack, Mundgefühl und Nachklang ein\n- stelle Charakter und Stil des Produkts hochwertig dar, ohne erfundene Fakten zu ergänzen\n- vermittle, zu welchem Genussmoment oder Anlass der Whisky besonders gut passt\n\nFormat:\n- gib ausschließlich sauberes HTML für die PrestaShop-Produktbeschreibung zurück\n- beginne mit einem atmosphärischen Absatz in <p>\n- ergänze eine Zwischenüberschrift in <h3> wie Verkostungsnotizen oder Charakter\n- füge 4 bis 6 prägnante Stichpunkte in einer <ul> mit <li>-Elementen ein\n- schließe mit einem kurzen, stilvollen Absatz zum Finish oder Genussmoment ab\n\nStil:\n- sommelier-artig, präzise, hochwertig und vertrauenswürdig\n- bildhaft und genussvoll, aber nicht kitschig oder übertrieben\n- keine Fantasieangaben, keine Hinweise auf KI, keine Emojis, keine Markdown-Codeblöcke";

$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Das Modul konnte nicht geladen werden.')] = 'Das Modul konnte nicht geladen werden.';
$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Der Produktname fehlt.')] = 'Der Produktname fehlt.';

$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültiges Sicherheitstoken. Bitte die Admin-Seite neu laden.')] = 'Ungültiges Sicherheitstoken. Bitte die Admin-Seite neu laden.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültige Aktion.')] = 'Ungültige Aktion.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Der Produktname fehlt.')] = 'Der Produktname fehlt.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Das Modul konnte nicht geladen werden.')] = 'Das Modul konnte nicht geladen werden.';
