<?php

global $_MODULE;
$_MODULE = array();

$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Internauten Product AI')] = 'Internauten Product AI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Erzeugt per ChatGPT eine Produktbeschreibung direkt im PrestaShop-Admin.')] = 'Generates a product description with ChatGPT directly in the PrestaShop admin.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Einstellungen wurden gespeichert.')] = 'The settings have been saved.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI-Einstellungen')] = 'OpenAI settings';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI API Key')] = 'OpenAI API key';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Trage hier deinen OpenAI API Key ein.')] = 'Enter your OpenAI API key here.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Modell')] = 'Model';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Empfohlen: gpt-4o-mini')] = 'Recommended: gpt-4o-mini';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('System-Prompt')] = 'System prompt';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Definiert Rolle, Stil und Verhalten des Modells.')] = 'Defines the model\'s role, style and behavior.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Prompt-Vorlage')] = 'Prompt template';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Nutze {{product_name}} als Platzhalter für den Artikelnamen.')] = 'Use {{product_name}} as the placeholder for the product name.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Speichern')] = 'Save';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Mit ChatGPT generieren')] = 'Generate with ChatGPT';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Beschreibung wird erstellt...')] = 'Generating description...';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Bitte zuerst einen Artikelnamen eintragen.')] = 'Please enter a product name first.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Beschreibung konnte nicht generiert werden.')] = 'The description could not be generated.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Fehler bei der Generierung.')] = 'Error while generating.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Der Server hat keine gültige JSON-Antwort geliefert:')] = 'The server returned no valid JSON response:';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('leere Antwort')] = 'empty response';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Es ist kein OpenAI API Key hinterlegt.')] = 'No OpenAI API key has been configured.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die PHP-cURL-Erweiterung ist auf dem Server nicht aktiviert.')] = 'The PHP cURL extension is not enabled on the server.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI konnte nicht erreicht werden: ')] = 'OpenAI could not be reached: ';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Unbekannter API-Fehler.')] = 'Unknown API error.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI hat keine Beschreibung zurückgegeben.')] = 'OpenAI did not return a description.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Du bist ein professioneller E-Commerce-Texter mit sommelier-artigem Stil und Fokus auf hochwertige Spirituosen, insbesondere Whisky. Erstelle elegante, sensorische und glaubwürdige HTML-Produktbeschreibungen für deutschsprachige Onlineshops. Betone bei Whisky – sofern aus dem Produktnamen plausibel ableitbar – Herkunft, Reifung, Duftbild, Geschmacksprofil, Textur und Nachklang. Wenn Details fehlen, bleibe stilvoll und allgemein, ohne Fakten zu erfinden. Die Sprache soll genussorientiert, präzise und hochwertig sein, aber nie übertrieben oder pathetisch. Antworte ausschließlich mit sauberem HTML ohne Markdown-Codeblöcke.')] = 'You are a professional e-commerce copywriter with a sommelier-like style and a focus on premium spirits, especially whisky. Create elegant, sensory and credible HTML product descriptions for English-language online shops. For whisky, emphasize origin, maturation, aroma, flavour profile, texture and finish whenever these details can plausibly be inferred from the product name. If details are missing, remain stylish and general without inventing facts. The tone should be pleasure-oriented, precise and premium, but never exaggerated or overly theatrical. Reply only with clean HTML and without Markdown code blocks.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5("Erstelle für das Produkt \"{{product_name}}\" eine sommelier-artige Produktbeschreibung für einen deutschsprachigen Onlineshop mit Fokus auf Whisky und Premium-Spirituosen.\n\nInhalt:\n- beschreibe den Whisky mit einer eleganten, sensorischen und genussorientierten Sprache\n- gehe, wenn aus dem Namen erkennbar, auf Herkunft, Fassreifung, Duft, Geschmack, Mundgefühl und Nachklang ein\n- stelle Charakter und Stil des Produkts hochwertig dar, ohne erfundene Fakten zu ergänzen\n- vermittle, zu welchem Genussmoment oder Anlass der Whisky besonders gut passt\n\nFormat:\n- gib ausschließlich sauberes HTML für die PrestaShop-Produktbeschreibung zurück\n- beginne mit einem atmosphärischen Absatz in <p>\n- ergänze eine Zwischenüberschrift in <h3> wie Verkostungsnotizen oder Charakter\n- füge 4 bis 6 prägnante Stichpunkte in einer <ul> mit <li>-Elementen ein\n- schließe mit einem kurzen, stilvollen Absatz zum Finish oder Genussmoment ab\n\nStil:\n- sommelier-artig, präzise, hochwertig und vertrauenswürdig\n- bildhaft und genussvoll, aber nicht kitschig oder übertrieben\n- keine Fantasieangaben, keine Hinweise auf KI, keine Emojis, keine Markdown-Codeblöcke")] = "Create a sommelier-style product description for the product \"{{product_name}}\" for an English-language online shop focused on whisky and premium spirits.\n\nContent:\n- describe the whisky using elegant, sensory and enjoyment-oriented language\n- where it can be inferred from the name, mention origin, cask maturation, aroma, flavour, mouthfeel and finish\n- present the product's character and style in a premium way without adding invented facts\n- convey the kind of moment or occasion for which the whisky is especially suitable\n\nFormat:\n- return only clean HTML for the PrestaShop product description\n- start with an atmospheric paragraph in <p>\n- add a subheading in <h3> such as Tasting Notes or Character\n- include 4 to 6 concise bullet points in a <ul> with <li> elements\n- finish with a short, elegant paragraph about the finish or the ideal moment of enjoyment\n\nStyle:\n- sommelier-like, precise, premium and trustworthy\n- vivid and indulgent, but not cheesy or overblown\n- no invented facts, no references to AI, no emojis, no Markdown code blocks";

$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Das Modul konnte nicht geladen werden.')] = 'The module could not be loaded.';
$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Der Produktname fehlt.')] = 'The product name is missing.';

$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültiges Sicherheitstoken. Bitte die Admin-Seite neu laden.')] = 'Invalid security token. Please reload the admin page.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültige Aktion.')] = 'Invalid action.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Der Produktname fehlt.')] = 'The product name is missing.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Das Modul konnte nicht geladen werden.')] = 'The module could not be loaded.';
