<?php

global $_MODULE;
$_MODULE = array();

$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Internauten Product AI')] = 'Internauten Product AI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Erzeugt per ChatGPT eine Produktbeschreibung direkt im PrestaShop-Admin.')] = 'Génère une description produit avec ChatGPT directement dans l\'administration PrestaShop.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Einstellungen wurden gespeichert.')] = 'Les paramètres ont été enregistrés.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI-Einstellungen')] = 'Paramètres OpenAI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI API Key')] = 'Clé API OpenAI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Trage hier deinen OpenAI API Key ein.')] = 'Saisissez ici votre clé API OpenAI.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Modell')] = 'Modèle';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Empfohlen: gpt-4o-mini')] = 'Recommandé : gpt-4o-mini';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('System-Prompt')] = 'Prompt système';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Definiert Rolle, Stil und Verhalten des Modells.')] = 'Définit le rôle, le style et le comportement du modèle.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Prompt-Vorlage')] = 'Modèle de prompt';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Nutze {{product_name}} als Platzhalter für den Artikelnamen.')] = 'Utilisez {{product_name}} comme variable pour le nom du produit.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Speichern')] = 'Enregistrer';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Mit ChatGPT generieren')] = 'Générer avec ChatGPT';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Beschreibung wird erstellt...')] = 'Génération de la description...';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Bitte zuerst einen Artikelnamen eintragen.')] = 'Veuillez d\'abord saisir un nom de produit.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Beschreibung konnte nicht generiert werden.')] = 'La description n\'a pas pu être générée.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Fehler bei der Generierung.')] = 'Erreur lors de la génération.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Der Server hat keine gültige JSON-Antwort geliefert:')] = 'Le serveur n\'a pas renvoyé de réponse JSON valide :';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('leere Antwort')] = 'réponse vide';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Es ist kein OpenAI API Key hinterlegt.')] = 'Aucune clé API OpenAI n\'est configurée.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die PHP-cURL-Erweiterung ist auf dem Server nicht aktiviert.')] = 'L\'extension PHP cURL n\'est pas activée sur le serveur.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI konnte nicht erreicht werden: ')] = 'Impossible de joindre OpenAI : ';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Unbekannter API-Fehler.')] = 'Erreur API inconnue.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI hat keine Beschreibung zurückgegeben.')] = 'OpenAI n\'a renvoyé aucune description.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Du bist ein professioneller E-Commerce-Texter mit sommelier-artigem Stil und Fokus auf hochwertige Spirituosen, insbesondere Whisky. Erstelle elegante, sensorische und glaubwürdige HTML-Produktbeschreibungen für deutschsprachige Onlineshops. Betone bei Whisky – sofern aus dem Produktnamen plausibel ableitbar – Herkunft, Reifung, Duftbild, Geschmacksprofil, Textur und Nachklang. Wenn Details fehlen, bleibe stilvoll und allgemein, ohne Fakten zu erfinden. Die Sprache soll genussorientiert, präzise und hochwertig sein, aber nie übertrieben oder pathetisch. Antworte ausschließlich mit sauberem HTML ohne Markdown-Codeblöcke.')] = 'Vous êtes un rédacteur e-commerce professionnel au style inspiré du sommelier, spécialisé dans les spiritueux haut de gamme, notamment le whisky. Rédigez des descriptions produit HTML élégantes, sensorielles et crédibles pour des boutiques en ligne francophones. Pour le whisky, mettez en avant l\'origine, le vieillissement, le nez, le profil aromatique, la texture et la finale lorsque ces éléments peuvent être déduits de façon plausible du nom du produit. Si des détails manquent, restez raffiné et général sans inventer de faits. Le ton doit être évocateur, précis et premium, sans jamais être excessif ni emphatique. Répondez uniquement avec du HTML propre, sans blocs de code Markdown.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5("Erstelle für das Produkt \"{{product_name}}\" eine sommelier-artige Produktbeschreibung für einen deutschsprachigen Onlineshop mit Fokus auf Whisky und Premium-Spirituosen.\n\nInhalt:\n- beschreibe den Whisky mit einer eleganten, sensorischen und genussorientierten Sprache\n- gehe, wenn aus dem Namen erkennbar, auf Herkunft, Fassreifung, Duft, Geschmack, Mundgefühl und Nachklang ein\n- stelle Charakter und Stil des Produkts hochwertig dar, ohne erfundene Fakten zu ergänzen\n- vermittle, zu welchem Genussmoment oder Anlass der Whisky besonders gut passt\n\nFormat:\n- gib ausschließlich sauberes HTML für die PrestaShop-Produktbeschreibung zurück\n- beginne mit einem atmosphärischen Absatz in <p>\n- ergänze eine Zwischenüberschrift in <h3> wie Verkostungsnotizen oder Charakter\n- füge 4 bis 6 prägnante Stichpunkte in einer <ul> mit <li>-Elementen ein\n- schließe mit einem kurzen, stilvollen Absatz zum Finish oder Genussmoment ab\n\nStil:\n- sommelier-artig, präzise, hochwertig und vertrauenswürdig\n- bildhaft und genussvoll, aber nicht kitschig oder übertrieben\n- keine Fantasieangaben, keine Hinweise auf KI, keine Emojis, keine Markdown-Codeblöcke")] = "Crée pour le produit \"{{product_name}}\" une description produit au style sommelier pour une boutique en ligne francophone axée sur le whisky et les spiritueux premium.\n\nContenu :\n- décris le whisky avec un langage élégant, sensoriel et orienté vers le plaisir de dégustation\n- lorsque le nom le permet, évoque l'origine, l'élevage en fût, le nez, le goût, la texture en bouche et la finale\n- mets en valeur le caractère et le style du produit de manière premium, sans ajouter de faits inventés\n- suggère le moment de dégustation ou l'occasion pour laquelle ce whisky convient particulièrement bien\n\nFormat :\n- renvoie uniquement du HTML propre pour la description produit PrestaShop\n- commence par un paragraphe évocateur dans <p>\n- ajoute un sous-titre en <h3> comme Notes de dégustation ou Caractère\n- insère 4 à 6 puces concises dans une <ul> avec des éléments <li>\n- termine par un court paragraphe élégant sur la finale ou le moment idéal de dégustation\n\nStyle :\n- style sommelier, précis, premium et fiable\n- imagé et gourmand, mais sans excès ni emphase kitsch\n- aucun fait inventé, aucune mention de l\'IA, aucun emoji, aucun bloc de code Markdown";

$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Das Modul konnte nicht geladen werden.')] = 'Le module n\'a pas pu être chargé.';
$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Der Produktname fehlt.')] = 'Le nom du produit est manquant.';

$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültiges Sicherheitstoken. Bitte die Admin-Seite neu laden.')] = 'Jeton de sécurité invalide. Veuillez recharger la page d\'administration.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültige Aktion.')] = 'Action invalide.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Der Produktname fehlt.')] = 'Le nom du produit est manquant.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Das Modul konnte nicht geladen werden.')] = 'Le module n\'a pas pu être chargé.';
