<?php

global $_MODULE;
$_MODULE = array();

$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Internauten Product AI')] = 'Internauten Product AI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Erzeugt per ChatGPT eine Produktbeschreibung direkt im PrestaShop-Admin.')] = 'Genera una descrizione prodotto con ChatGPT direttamente nel pannello di amministrazione di PrestaShop.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Einstellungen wurden gespeichert.')] = 'Le impostazioni sono state salvate.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI-Einstellungen')] = 'Impostazioni OpenAI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI API Key')] = 'Chiave API OpenAI';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Trage hier deinen OpenAI API Key ein.')] = 'Inserisci qui la tua chiave API OpenAI.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Modell')] = 'Modello';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Empfohlen: gpt-4o-mini')] = 'Consigliato: gpt-4o-mini';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('System-Prompt')] = 'Prompt di sistema';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Definiert Rolle, Stil und Verhalten des Modells.')] = 'Definisce ruolo, stile e comportamento del modello.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Prompt-Vorlage')] = 'Modello di prompt';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Nutze {{product_name}} als Platzhalter für den Artikelnamen.')] = 'Usa {{product_name}} come segnaposto per il nome del prodotto.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Speichern')] = 'Salva';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Mit ChatGPT generieren')] = 'Genera con ChatGPT';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Beschreibung wird erstellt...')] = 'Generazione della descrizione...';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Bitte zuerst einen Artikelnamen eintragen.')] = 'Inserisci prima il nome del prodotto.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die Beschreibung konnte nicht generiert werden.')] = 'Non è stato possibile generare la descrizione.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Fehler bei der Generierung.')] = 'Errore durante la generazione.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Der Server hat keine gültige JSON-Antwort geliefert:')] = 'Il server non ha restituito una risposta JSON valida:';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('leere Antwort')] = 'risposta vuota';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Es ist kein OpenAI API Key hinterlegt.')] = 'Non è stata configurata alcuna chiave API OpenAI.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Die PHP-cURL-Erweiterung ist auf dem Server nicht aktiviert.')] = 'L\'estensione PHP cURL non è attivata sul server.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI konnte nicht erreicht werden: ')] = 'Impossibile contattare OpenAI: ';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Unbekannter API-Fehler.')] = 'Errore API sconosciuto.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('OpenAI hat keine Beschreibung zurückgegeben.')] = 'OpenAI non ha restituito alcuna descrizione.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5('Du bist ein professioneller E-Commerce-Texter mit sommelier-artigem Stil und Fokus auf hochwertige Spirituosen, insbesondere Whisky. Erstelle elegante, sensorische und glaubwürdige HTML-Produktbeschreibungen für deutschsprachige Onlineshops. Betone bei Whisky – sofern aus dem Produktnamen plausibel ableitbar – Herkunft, Reifung, Duftbild, Geschmacksprofil, Textur und Nachklang. Wenn Details fehlen, bleibe stilvoll und allgemein, ohne Fakten zu erfinden. Die Sprache soll genussorientiert, präzise und hochwertig sein, aber nie übertrieben oder pathetisch. Antworte ausschließlich mit sauberem HTML ohne Markdown-Codeblöcke.')] = 'Sei un copywriter professionista per l\'e-commerce con uno stile da sommelier e un focus su distillati di alta qualità, in particolare il whisky. Crea descrizioni prodotto in HTML eleganti, sensoriali e credibili per negozi online in lingua italiana. Per il whisky, evidenzia origine, maturazione, profilo aromatico, gusto, texture e finale quando questi elementi possono essere plausibilmente dedotti dal nome del prodotto. Se mancano dettagli, resta raffinato e generale senza inventare fatti. Il tono deve essere coinvolgente, preciso e premium, ma mai esagerato o teatrale. Rispondi esclusivamente con HTML pulito, senza blocchi di codice Markdown.';
$_MODULE['<{internautenproductai}prestashop>internautenproductai_' . md5("Erstelle für das Produkt \"{{product_name}}\" eine sommelier-artige Produktbeschreibung für einen deutschsprachigen Onlineshop mit Fokus auf Whisky und Premium-Spirituosen.\n\nInhalt:\n- beschreibe den Whisky mit einer eleganten, sensorischen und genussorientierten Sprache\n- gehe, wenn aus dem Namen erkennbar, auf Herkunft, Fassreifung, Duft, Geschmack, Mundgefühl und Nachklang ein\n- stelle Charakter und Stil des Produkts hochwertig dar, ohne erfundene Fakten zu ergänzen\n- vermittle, zu welchem Genussmoment oder Anlass der Whisky besonders gut passt\n\nFormat:\n- gib ausschließlich sauberes HTML für die PrestaShop-Produktbeschreibung zurück\n- beginne mit einem atmosphärischen Absatz in <p>\n- ergänze eine Zwischenüberschrift in <h3> wie Verkostungsnotizen oder Charakter\n- füge 4 bis 6 prägnante Stichpunkte in einer <ul> mit <li>-Elementen ein\n- schließe mit einem kurzen, stilvollen Absatz zum Finish oder Genussmoment ab\n\nStil:\n- sommelier-artig, präzise, hochwertig und vertrauenswürdig\n- bildhaft und genussvoll, aber nicht kitschig oder übertrieben\n- keine Fantasieangaben, keine Hinweise auf KI, keine Emojis, keine Markdown-Codeblöcke")] = "Crea per il prodotto \"{{product_name}}\" una descrizione sommelier per un negozio online in lingua italiana specializzato in whisky e distillati premium.\n\nContenuto:\n- descrivi il whisky con un linguaggio elegante, sensoriale e orientato al piacere della degustazione\n- se il nome lo suggerisce, menziona origine, affinamento in botte, profumo, gusto, sensazione al palato e finale\n- presenta il carattere e lo stile del prodotto in modo premium, senza aggiungere fatti inventati\n- comunica per quale momento di consumo o occasione il whisky è particolarmente adatto\n\nFormato:\n- restituisci esclusivamente HTML pulito per la descrizione prodotto di PrestaShop\n- inizia con un paragrafo evocativo in <p>\n- aggiungi un sottotitolo in <h3> come Note di degustazione o Carattere\n- inserisci da 4 a 6 punti elenco concisi in una <ul> con elementi <li>\n- concludi con un breve paragrafo elegante sul finale o sul momento ideale di degustazione\n\nStile:\n- da sommelier, preciso, premium e affidabile\n- evocativo e piacevole, ma non sdolcinato né eccessivo\n- nessun fatto inventato, nessun riferimento all\'IA, nessuna emoji, nessun blocco di codice Markdown";

$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Das Modul konnte nicht geladen werden.')] = 'Impossibile caricare il modulo.';
$_MODULE['<{internautenproductai}prestashop>admininternautenproductaigeneratecontroller_' . md5('Der Produktname fehlt.')] = 'Manca il nome del prodotto.';

$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültiges Sicherheitstoken. Bitte die Admin-Seite neu laden.')] = 'Token di sicurezza non valido. Ricarica la pagina di amministrazione.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Ungültige Aktion.')] = 'Azione non valida.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Der Produktname fehlt.')] = 'Manca il nome del prodotto.';
$_MODULE['<{internautenproductai}prestashop>ajax_' . md5('Das Modul konnte nicht geladen werden.')] = 'Impossibile caricare il modulo.';
